language: rust

cache: cargo

matrix:
  include:
    - name: cargo test
      rust: stable
      os: osx

    - name: cargo test
      rust: nightly
      os: osx

    - name: cargo test
      rust: stable
      os: linux
      env: CRATES_IO_PUBLISH=true

    - name: cargo test
      rust: nightly
      os: linux

install: |
  if [ "$TRAVIS_RUST_VERSION" != nightly ]; then
    rustup component add clippy
  fi

script:
  - cargo test --all --all-features
  - cargo test --all --all-features --release
  - |
    if [ "$TRAVIS_RUST_VERSION" != nightly ]; then
      cargo clippy
    fi

deploy:
  provider: script
  script:
    - cargo publish --token "${CRATES_IO_TOKEN}"
  on:
    tags: true
    all_branches: true
    condition: $CRATES_IO_PUBLISH = true

notifications:
  email:
    on_success: never
